name: Node Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Install dev dependencies
        run: npm install eslint eslint-config-standard eslint-plugin-mocha eslint-plugin-node eslint-plugin-standard mocha nock node-red node-red-node-test-helper package.json should --save-dep
      - name: Install Others
        run: npm install --production=false
      - run: npm test
